fix: patch appstream data
Flatpak builder added strict validation and requires "developer"
information to be provided. Upstream metadata is missing this key.

This commit patches provided appstream data until upstream added missing
information themselves.

Build error:

```
Run docker run --rm --privileged \
+ flatpak-builder-lint --exceptions repo repo
{
    "errors": [
        "appstream-missing-developer-name"
    ],
    "warnings": [
        "appstream-screenshot-missing-caption"
    ],
    "info": [
        "appstream-screenshot-missing-caption: One or more screenshots
are missing captions in the Metainfo file",
        "appstream-missing-developer-name: No developer tag found in
Metainfo file"
    ],
    "message": "Please consult the documentation at
https://docs.flathub.org/docs/for-app-authors/linter"
}
error: Recipe `validate-build` failed with exit code 1
```